NIFTY_50_STOCKS = [
    {"symbol": "RELIANCE", "name": "Reliance Industries", "yf_symbol": "RELIANCE.NS"},
    {"symbol": "TCS", "name": "Tata Consultancy Services", "yf_symbol": "TCS.NS"},
    {"symbol": "HDFCBANK", "name": "HDFC Bank", "yf_symbol": "HDFCBANK.NS"},
    {"symbol": "ICICIBANK", "name": "ICICI Bank", "yf_symbol": "ICICIBANK.NS"},
    {"symbol": "INFY", "name": "Infosys", "yf_symbol": "INFY.NS"},
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel", "yf_symbol": "BHARTIARTL.NS"},
    {"symbol": "ITC", "name": "ITC", "yf_symbol": "ITC.NS"},
    {"symbol": "LT", "name": "Larsen & Toubro", "yf_symbol": "LT.NS"},
    {"symbol": "SBIN", "name": "State Bank of India", "yf_symbol": "SBIN.NS"},
    {"symbol": "AXISBANK", "name": "Axis Bank", "yf_symbol": "AXISBANK.NS"},
    {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank", "yf_symbol": "KOTAKBANK.NS"},
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever", "yf_symbol": "HINDUNILVR.NS"},
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance", "yf_symbol": "BAJFINANCE.NS"},
    {"symbol": "ASIANPAINT", "name": "Asian Paints", "yf_symbol": "ASIANPAINT.NS"},
    {"symbol": "MARUTI", "name": "Maruti Suzuki", "yf_symbol": "MARUTI.NS"},
    {"symbol": "SUNPHARMA", "name": "Sun Pharma", "yf_symbol": "SUNPHARMA.NS"},
    {"symbol": "TITAN", "name": "Titan Company", "yf_symbol": "TITAN.NS"},
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement", "yf_symbol": "ULTRACEMCO.NS"},
    {"symbol": "WIPRO", "name": "Wipro", "yf_symbol": "WIPRO.NS"},
    {"symbol": "NESTLEIND", "name": "Nestle India", "yf_symbol": "NESTLEIND.NS"},
    {"symbol": "HCLTECH", "name": "HCL Technologies", "yf_symbol": "HCLTECH.NS"},
    {"symbol": "ONGC", "name": "Oil and Natural Gas Corp", "yf_symbol": "ONGC.NS"},
    {"symbol": "NTPC", "name": "NTPC", "yf_symbol": "NTPC.NS"},
    {"symbol": "POWERGRID", "name": "Power Grid Corp", "yf_symbol": "POWERGRID.NS"},
    {"symbol": "M&M", "name": "Mahindra & Mahindra", "yf_symbol": "M&M.NS"},
    {"symbol": "TATAMOTORS", "name": "Tata Motors", "yf_symbol": "TATAMOTORS.NS"},
    {"symbol": "TATASTEEL", "name": "Tata Steel", "yf_symbol": "TATASTEEL.NS"},
    {"symbol": "JSWSTEEL", "name": "JSW Steel", "yf_symbol": "JSWSTEEL.NS"},
    {"symbol": "COALINDIA", "name": "Coal India", "yf_symbol": "COALINDIA.NS"},
    {"symbol": "ADANIENT", "name": "Adani Enterprises", "yf_symbol": "ADANIENT.NS"},
    {"symbol": "ADANIPORTS", "name": "Adani Ports", "yf_symbol": "ADANIPORTS.NS"},
    {"symbol": "GRASIM", "name": "Grasim Industries", "yf_symbol": "GRASIM.NS"},
    {"symbol": "CIPLA", "name": "Cipla", "yf_symbol": "CIPLA.NS"},
    {"symbol": "DRREDDY", "name": "Dr. Reddy's Labs", "yf_symbol": "DRREDDY.NS"},
    {"symbol": "DIVISLAB", "name": "Divi's Laboratories", "yf_symbol": "DIVISLAB.NS"},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv", "yf_symbol": "BAJAJFINSV.NS"},
    {"symbol": "BAJAJ-AUTO", "name": "Bajaj Auto", "yf_symbol": "BAJAJ-AUTO.NS"},
    {"symbol": "EICHERMOT", "name": "Eicher Motors", "yf_symbol": "EICHERMOT.NS"},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp", "yf_symbol": "HEROMOTOCO.NS"},
    {"symbol": "BRITANNIA", "name": "Britannia Industries", "yf_symbol": "BRITANNIA.NS"},
    {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals", "yf_symbol": "APOLLOHOSP.NS"},
    {"symbol": "BPCL", "name": "Bharat Petroleum", "yf_symbol": "BPCL.NS"},
    {"symbol": "HINDALCO", "name": "Hindalco Industries", "yf_symbol": "HINDALCO.NS"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank", "yf_symbol": "INDUSINDBK.NS"},
    {"symbol": "TECHM", "name": "Tech Mahindra", "yf_symbol": "TECHM.NS"},
    {"symbol": "UPL", "name": "UPL", "yf_symbol": "UPL.NS"},
    {"symbol": "SBILIFE", "name": "SBI Life Insurance", "yf_symbol": "SBILIFE.NS"},
    {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance", "yf_symbol": "HDFCLIFE.NS"},
    {"symbol": "SHRIRAMFIN", "name": "Shriram Finance", "yf_symbol": "SHRIRAMFIN.NS"},
    {"symbol": "LTIM", "name": "LTIMindtree", "yf_symbol": "LTIM.NS"},
]


def stock_by_symbol(symbol: str):
    normalized = symbol.upper()
    return next((stock for stock in NIFTY_50_STOCKS if stock["symbol"] == normalized), None)
