NIFTY_50_STOCKS = [
    {"symbol": "RELIANCE",   "name": "Reliance Industries",        "yf_symbol": "RELIANCE.NS",   "sector": "Energy"},
    {"symbol": "TCS",        "name": "Tata Consultancy Services",  "yf_symbol": "TCS.NS",        "sector": "IT"},
    {"symbol": "HDFCBANK",   "name": "HDFC Bank",                  "yf_symbol": "HDFCBANK.NS",   "sector": "Banking"},
    {"symbol": "ICICIBANK",  "name": "ICICI Bank",                 "yf_symbol": "ICICIBANK.NS",  "sector": "Banking"},
    {"symbol": "INFY",       "name": "Infosys",                    "yf_symbol": "INFY.NS",       "sector": "IT"},
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel",              "yf_symbol": "BHARTIARTL.NS", "sector": "Telecom"},
    {"symbol": "ITC",        "name": "ITC",                        "yf_symbol": "ITC.NS",        "sector": "FMCG"},
    {"symbol": "LT",         "name": "Larsen & Toubro",            "yf_symbol": "LT.NS",         "sector": "Capital Goods"},
    {"symbol": "SBIN",       "name": "State Bank of India",        "yf_symbol": "SBIN.NS",       "sector": "Banking"},
    {"symbol": "AXISBANK",   "name": "Axis Bank",                  "yf_symbol": "AXISBANK.NS",   "sector": "Banking"},
    {"symbol": "KOTAKBANK",  "name": "Kotak Mahindra Bank",        "yf_symbol": "KOTAKBANK.NS",  "sector": "Banking"},
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever",         "yf_symbol": "HINDUNILVR.NS", "sector": "FMCG"},
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance",              "yf_symbol": "BAJFINANCE.NS", "sector": "NBFC"},
    {"symbol": "ASIANPAINT", "name": "Asian Paints",               "yf_symbol": "ASIANPAINT.NS", "sector": "FMCG"},
    {"symbol": "MARUTI",     "name": "Maruti Suzuki",              "yf_symbol": "MARUTI.NS",     "sector": "Auto"},
    {"symbol": "SUNPHARMA",  "name": "Sun Pharma",                 "yf_symbol": "SUNPHARMA.NS",  "sector": "Pharma"},
    {"symbol": "TITAN",      "name": "Titan Company",              "yf_symbol": "TITAN.NS",      "sector": "Consumer"},
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement",           "yf_symbol": "ULTRACEMCO.NS", "sector": "Cement"},
    {"symbol": "WIPRO",      "name": "Wipro",                      "yf_symbol": "WIPRO.NS",      "sector": "IT"},
    {"symbol": "NESTLEIND",  "name": "Nestle India",               "yf_symbol": "NESTLEIND.NS",  "sector": "FMCG"},
    {"symbol": "HCLTECH",    "name": "HCL Technologies",           "yf_symbol": "HCLTECH.NS",    "sector": "IT"},
    {"symbol": "ONGC",       "name": "Oil and Natural Gas Corp",   "yf_symbol": "ONGC.NS",       "sector": "Energy"},
    {"symbol": "NTPC",       "name": "NTPC",                       "yf_symbol": "NTPC.NS",       "sector": "Power"},
    {"symbol": "POWERGRID",  "name": "Power Grid Corp",            "yf_symbol": "POWERGRID.NS",  "sector": "Power"},
    {"symbol": "MM",         "name": "Mahindra & Mahindra",        "yf_symbol": "M&M.NS",        "sector": "Auto"},
    {"symbol": "TATAMOTORS", "name": "Tata Motors",                "yf_symbol": "TATAMOTORS.NS", "sector": "Auto"},
    {"symbol": "TATASTEEL",  "name": "Tata Steel",                 "yf_symbol": "TATASTEEL.NS",  "sector": "Metals"},
    {"symbol": "JSWSTEEL",   "name": "JSW Steel",                  "yf_symbol": "JSWSTEEL.NS",   "sector": "Metals"},
    {"symbol": "COALINDIA",  "name": "Coal India",                 "yf_symbol": "COALINDIA.NS",  "sector": "Energy"},
    {"symbol": "ADANIENT",   "name": "Adani Enterprises",          "yf_symbol": "ADANIENT.NS",   "sector": "Conglomerate"},
    {"symbol": "ADANIPORTS", "name": "Adani Ports",                "yf_symbol": "ADANIPORTS.NS", "sector": "Infrastructure"},
    {"symbol": "GRASIM",     "name": "Grasim Industries",          "yf_symbol": "GRASIM.NS",     "sector": "Cement"},
    {"symbol": "CIPLA",      "name": "Cipla",                      "yf_symbol": "CIPLA.NS",      "sector": "Pharma"},
    {"symbol": "DRREDDY",    "name": "Dr. Reddy's Labs",           "yf_symbol": "DRREDDY.NS",    "sector": "Pharma"},
    {"symbol": "DIVISLAB",   "name": "Divi's Laboratories",        "yf_symbol": "DIVISLAB.NS",   "sector": "Pharma"},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv",              "yf_symbol": "BAJAJFINSV.NS", "sector": "NBFC"},
    {"symbol": "BAJAJAUTO",  "name": "Bajaj Auto",                 "yf_symbol": "BAJAJ-AUTO.NS", "sector": "Auto"},
    {"symbol": "EICHERMOT",  "name": "Eicher Motors",              "yf_symbol": "EICHERMOT.NS",  "sector": "Auto"},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp",              "yf_symbol": "HEROMOTOCO.NS", "sector": "Auto"},
    {"symbol": "BRITANNIA",  "name": "Britannia Industries",       "yf_symbol": "BRITANNIA.NS",  "sector": "FMCG"},
    {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals",           "yf_symbol": "APOLLOHOSP.NS", "sector": "Healthcare"},
    {"symbol": "BPCL",       "name": "Bharat Petroleum",           "yf_symbol": "BPCL.NS",       "sector": "Energy"},
    {"symbol": "HINDALCO",   "name": "Hindalco Industries",        "yf_symbol": "HINDALCO.NS",   "sector": "Metals"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank",              "yf_symbol": "INDUSINDBK.NS", "sector": "Banking"},
    {"symbol": "TECHM",      "name": "Tech Mahindra",              "yf_symbol": "TECHM.NS",      "sector": "IT"},
    {"symbol": "UPL",        "name": "UPL",                        "yf_symbol": "UPL.NS",        "sector": "Chemicals"},
    {"symbol": "SBILIFE",    "name": "SBI Life Insurance",         "yf_symbol": "SBILIFE.NS",    "sector": "Insurance"},
    {"symbol": "HDFCLIFE",   "name": "HDFC Life Insurance",        "yf_symbol": "HDFCLIFE.NS",   "sector": "Insurance"},
    {"symbol": "SHRIRAMFIN", "name": "Shriram Finance",            "yf_symbol": "SHRIRAMFIN.NS", "sector": "NBFC"},
    {"symbol": "LTIM",       "name": "LTIMindtree",                "yf_symbol": "LTIM.NS",       "sector": "IT"},
]

NIFTY_INDEX = {"symbol": "^NSEI", "name": "NIFTY 50 Index", "yf_symbol": "^NSEI"}


def stock_by_symbol(symbol: str):
    normalized = symbol.upper()
    return next((s for s in NIFTY_50_STOCKS if s["symbol"] == normalized), None)
