/** Mirror of backend nifty50.py for use in frontend dropdowns */
export const NIFTY_50_STOCKS = [
  { symbol: "RELIANCE",   name: "Reliance Industries" },
  { symbol: "TCS",        name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK",   name: "HDFC Bank" },
  { symbol: "ICICIBANK",  name: "ICICI Bank" },
  { symbol: "INFY",       name: "Infosys" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "ITC",        name: "ITC" },
  { symbol: "LT",         name: "Larsen & Toubro" },
  { symbol: "SBIN",       name: "State Bank of India" },
  { symbol: "AXISBANK",   name: "Axis Bank" },
  { symbol: "KOTAKBANK",  name: "Kotak Mahindra Bank" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "MARUTI",     name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA",  name: "Sun Pharma" },
  { symbol: "TITAN",      name: "Titan Company" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "WIPRO",      name: "Wipro" },
  { symbol: "NESTLEIND",  name: "Nestle India" },
  { symbol: "HCLTECH",    name: "HCL Technologies" },
  { symbol: "ONGC",       name: "Oil and Natural Gas Corp" },
  { symbol: "NTPC",       name: "NTPC" },
  { symbol: "POWERGRID",  name: "Power Grid Corp" },
  { symbol: "MM",         name: "Mahindra & Mahindra" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "TATASTEEL",  name: "Tata Steel" },
  { symbol: "JSWSTEEL",   name: "JSW Steel" },
  { symbol: "COALINDIA",  name: "Coal India" },
  { symbol: "ADANIENT",   name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "GRASIM",     name: "Grasim Industries" },
  { symbol: "CIPLA",      name: "Cipla" },
  { symbol: "DRREDDY",    name: "Dr. Reddy's Labs" },
  { symbol: "DIVISLAB",   name: "Divi's Laboratories" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "BAJAJAUTO",  name: "Bajaj Auto" },
  { symbol: "EICHERMOT",  name: "Eicher Motors" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "BRITANNIA",  name: "Britannia Industries" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "BPCL",       name: "Bharat Petroleum" },
  { symbol: "HINDALCO",   name: "Hindalco Industries" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "TECHM",      name: "Tech Mahindra" },
  { symbol: "UPL",        name: "UPL" },
  { symbol: "SBILIFE",    name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE",   name: "HDFC Life Insurance" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "LTIM",       name: "LTIMindtree" },
] as const;
